name: CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14.x
      - name: Installing dependencies
        run: yarn
      - name: Generating build
        run: yarn build
      - name: Deploying
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_HOST_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "/srv/gobarber-api"
      - name: Setup project in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_HOST_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/gobarber-api
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart gobarber-api


